"""Add standards registry, enforcement cases, and repair records

Revision ID: 9e718e1dbb07
Revises: fdb3232bcfc0
Create Date: 2026-09-30 00:59:14.165284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e718e1dbb07'
down_revision = 'fdb3232bcfc0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###