"""Fix requirement model enum types

Revision ID: c967248701ba
Revises: f5cc7e2b82cf
Create Date: 2026-09-29 22:53:14.774904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c967248701ba'
down_revision = 'f5cc7e2b82cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###