"""Add verification requirements and checklist templates

Revision ID: f5cc7e2b82cf
Revises: 001
Create Date: 2026-09-29 22:36:05.564750

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'f5cc7e2b82cf'
down_revision = '001'
branch_labels = None
depends_on = None


instrument_category_enum = postgresql.ENUM(
    'weighing_non_automatic', 'weighing_automatic', 'measuring_length', 'measuring_volume', 'measuring_flow', 'other',
    name='instrumentcategory', create_type=False
)

requirement_source_type_enum = postgresql.ENUM(
    'LEGAL_METROLOGY_ACT', 'GENERAL_RULES', 'STATE_RULES', 'OFFICIAL_NOTIFICATION', 'OTHER',
    name='requirementsourcetype', create_type=False
)


def upgrade() -> None:
    # Create enum types if they don't exist
    instrument_category_enum.create(op.get_bind(), checkfirst=True)
    requirement_source_type_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_category', instrument_category_enum, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('source_requirement_ids', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('effective_from', sa.DateTime(), nullable=False),
    sa.Column('effective_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_checklist_template_category_active', 'checklist_templates', ['instrument_category', 'is_active'], unique=False)
    op.create_index(op.f('ix_checklist_templates_id'), 'checklist_templates', ['id'], unique=False)
    op.create_index(op.f('ix_checklist_templates_instrument_category'), 'checklist_templates', ['instrument_category'], unique=False)
    op.create_table('verification_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_category', instrument_category_enum, nullable=False),
    sa.Column('requirement_code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_type', requirement_source_type_enum, nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=False),
    sa.Column('source_section', sa.String(length=100), nullable=True),
    sa.Column('effective_from', sa.DateTime(), nullable=False),
    sa.Column('effective_until', sa.DateTime(), nullable=True),
    sa.Column('jurisdiction', sa.String(length=255), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_requirement_category_effective', 'verification_requirements', ['instrument_category', 'effective_from'], unique=False)
    op.create_index('ix_requirement_source', 'verification_requirements', ['source_type', 'source_reference'], unique=False)
    op.create_index(op.f('ix_verification_requirements_id'), 'verification_requirements', ['id'], unique=False)
    op.create_index(op.f('ix_verification_requirements_instrument_category'), 'verification_requirements', ['instrument_category'], unique=False)
    op.create_table('checklist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('expected_result', sa.Text(), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['checklist_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklist_items_id'), 'checklist_items', ['id'], unique=False)
    op.create_index(op.f('ix_checklist_items_template_id'), 'checklist_items', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_checklist_items_template_id'), table_name='checklist_items')
    op.drop_index(op.f('ix_checklist_items_id'), table_name='checklist_items')
    op.drop_table('checklist_items')
    op.drop_index(op.f('ix_verification_requirements_instrument_category'), table_name='verification_requirements')
    op.drop_index(op.f('ix_verification_requirements_id'), table_name='verification_requirements')
    op.drop_index('ix_requirement_source', table_name='verification_requirements')
    op.drop_index('ix_requirement_category_effective', table_name='verification_requirements')
    op.drop_table('verification_requirements')
    op.drop_index(op.f('ix_checklist_templates_instrument_category'), table_name='checklist_templates')
    op.drop_index(op.f('ix_checklist_templates_id'), table_name='checklist_templates')
    op.drop_index('ix_checklist_template_category_active', table_name='checklist_templates')
    op.drop_table('checklist_templates')
    
    # Drop enum types
    requirement_source_type_enum.drop(op.get_bind(), checkfirst=True)
    # Note: instrumentcategory enum is used by other tables, so we don't drop it here
    # ### end Alembic commands ###